services:
  db:
    image: postgres:16-alpine
    container_name: checkout-postgres
    command: ['postgres', '-p', '5422']
    environment:
      POSTGRES_DB: credit_card_checkout
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5422:5422'
    volumes:
      - credit-card-payment-checkout-back_postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: checkout-backend
    depends_on:
      - db
    ports:
      - '3210:3210'
    environment:
      PORT: 3210
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@db:5422/credit_card_checkout?schema=public
      PAYMENT_GATEWAY_SANDBOX_URL: ${PAYMENT_GATEWAY_SANDBOX_URL}
      PAYMENT_GATEWAY_PUBLIC_KEY: ${PAYMENT_GATEWAY_PUBLIC_KEY}
      PAYMENT_GATEWAY_PRIVATE_KEY: ${PAYMENT_GATEWAY_PRIVATE_KEY}
      PAYMENT_GATEWAY_EVENTS_KEY: ${PAYMENT_GATEWAY_EVENTS_KEY}
      PAYMENT_GATEWAY_INTEGRITY_KEY: ${PAYMENT_GATEWAY_INTEGRITY_KEY}
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3210/health']
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  credit-card-payment-checkout-back_postgres_data:
